version: '3'
services:
 # The Application
  gep-auth-app:
    image: 196.190.41.213:5000/egov/gep-auth-app 
    working_dir: /var/www
    container_name: gep-auth-app
    volumes:
      - /var/www/storage
    env_file: '.env'
    environment:
      - "DB_HOST=gep-auth-db"
    networks:
      - app-network 
    restart: always
    tty: true
#The Web Server
  gep-auth-web:
    image: 196.190.41.213:5000/egov/gep-auth-web
    ports:
      - 9024:80
      - 748:443
    container_name: gep-auth-web
    networks:
      - app-network 
    restart: always
    tty: true
#The Database
  gep-auth-db:
    image: mariadb:latest
    container_name: gep-auth-db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=AuthServer"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    networks:
      - app-network 
#Docker Networks
networks:
  app-network:
    driver: bridge
#Docker Volumes
volumes:
  dbdata:
